SECTION="NetPing modules"
CATEGORY="Base"
TITLE="OWRT-snmp-agent"

PKG_NAME="OWRT-snmp-agent"
PKG_VERSION="0.1"
PKG_RELEASE=10
PKG_DEPENDS=OWRT-log ubus-0.1.1 snmpd

ETC_FILES=owrt-snmp-agent-init.py owrt-snmp-pass-agent.py
ETC_FILES_DIR=/etc/netping/$(PKG_NAME)/

TESTS_SRC_DIR=Tests

AUTORUN_FILES=owrt-snmp-agent-autorun

INSTALL_DIR=

.PHONY: all install

all: build preinstall install configure

ipk: build install

build:
	@echo "Nothing to do"

preinstall:
	@echo "Nothing to do"

configure:
	@echo "Nothing to do"

install:
ifneq ($(INSTALL_DIR),)
	mkdir -p $(INSTALL_DIR)/etc/init.d
	mkdir -p $(INSTALL_DIR)/etc/rc.d
endif
	mkdir -p $(INSTALL_DIR)$(ETC_FILES_DIR)
	for f in $(ETC_FILES); do cp etc/$${f} $(INSTALL_DIR)$(ETC_FILES_DIR); done
	cp -r $(TESTS_SRC_DIR) $(INSTALL_DIR)$(ETC_FILES_DIR)
	for f in $(AUTORUN_FILES); do cp $${f} $(INSTALL_DIR)/etc/init.d; done
	mv $(INSTALL_DIR)/etc/init.d/owrt-snmp-agent-autorun $(INSTALL_DIR)/etc/init.d/owrt-snmp-agent
	ln -s ../init.d/owrt-snmp-agent $(INSTALL_DIR)/etc/rc.d/S90OWRT-snmp-agent

clean:
ifeq ($(INSTALL_DIR),)
	rm -rf $(ETC_FILES_DIR)
	rm -f /etc/init.d/owrt-snmp-agent
	rm -f /etc/rc.d/S90OWRT-snmp-agent
else
	rm -rf $(INSTALL_DIR)
endif
