SECTION="NetPing modules"
CATEGORY="Base"
TITLE="OWRT-snmp-agent"

PKG_NAME="OWRT-snmp-agent"
PKG_VERSION="0.1"
PKG_RELEASE=1
PKG_DEPENDS=OWRT-log

ETC_FILES=owrt-snmp-agent.py
ETC_FILES_DIR=/etc/netping_snmp_agent/

INSTALL_DIR=

.PHONY: all install

all: configure build install

configure:
	@echo "Nothing to do"

build:
	@echo "Nothing to do"

# packages required to work:
# 1) opkg install snmpd
# 2) python ubus
install:
	mkdir -p $(INSTALL_DIR)$(ETC_FILES_DIR)
	for f in $(ETC_FILES); do cp etc/$${f} $(INSTALL_DIR)$(ETC_FILES_DIR); done

clean:
	rm -rf $(INSTALL_DIR)$(ETC_FILES_DIR)
